@startuml StayOn_Use_Case_Diagram

left to right direction

actor Student
actor Monitor

rectangle "StayOn System" {

  ' Common Function Group
  package "Common Functions" {
    usecase "Login" as UC1
    usecase "Register" as UC2
    usecase "Edit profile information" as UC3
    usecase "Comment on posts" as UC4
    usecase "Give feedback" as UC5
  }

  ' Monitor-Specific Functions
  package "Monitor Functions" {
    usecase "Publish study material" as UC6
    usecase "Organize meetings" as UC7
  }

  ' Student-Specific Functions
  package "Student Functions" {
    usecase "Follow" as UC8
    usecase "Rate monitors" as UC9
    usecase "View study material" as UC10
  }
}

' Student Relationships
together {
    Student -[#green]-> UC1
    Student -[#green]-> UC2
    Student -[#green]-> UC3
    Student -[#green]-> UC4
    Student -[#green]-> UC5
    Student -[#green]-> UC8
    Student -[#green]-> UC9
    Student -[#green]-> UC10
}


' Monitor Relationships
together {
    Monitor -[#blue]-> UC1
    Monitor -[#blue]-> UC2
    Monitor -[#blue]-> UC3
    Monitor -[#blue]-> UC4
    Monitor -[#blue]-> UC5
    Monitor -[#blue]-> UC6
    Monitor -[#blue]-> UC7
}


' Includes and Extends relationships
UC9 <. UC5 : <<extend>>
UC10 .> UC6 : <<include>>

@enduml
